In [ ]:
import numpy as np

In [ ]:
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])
A

array([[1, 2],
       [3, 4]])

In [ ]:
B

array([[5, 6],
       [7, 8]])

In [ ]:
A @ B

array([[19, 22],
       [43, 50]])

In [ ]:
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [ ]:
A.T

array([[1, 3],
       [2, 4]])

In [ ]:
B.T

array([[5, 7],
       [6, 8]])

In [ ]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])

In [ ]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [ ]:
np.row_stack((a,b))

/tmp/ipykernel_1059/1307586492.py:1: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  np.row_stack((a,b))


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
c=np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
arr=np.hsplit(c,2)
arr

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [ ]:
arr=np.hsplit(c,4)
arr

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [ ]:
arr=np.vsplit(c,4)
arr

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]