In [ ]:
import numpy as np

In [ ]:
arr = np.arange(11,21)

In [ ]:
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
arr[7]

np.int64(18)

In [ ]:
arr[1:5]

array([12, 13, 14, 15])

In [ ]:
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
arr=np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [ ]:
arr[0]

array([1, 2, 3, 4, 5])

In [ ]:
arr[0:6,1]

array([ 2,  7, 12, 17, 22, 27])

In [ ]:
arr[3:6,3:5]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [ ]:
arr[:,2]

array([ 3,  8, 13, 18, 23, 28])

In [ ]:
arr=np.arange(11,21)

In [ ]:
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
arr=np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
bool_index = arr %2 == 1
bool_index

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [ ]:
arr = arr[bool_index]
arr

array([11, 13, 15, 17, 19])

In [ ]:
a1=np.array([1,2,3,4,5])
a2=np.array([6,7,8,9,10])
a1
a2

array([ 6,  7,  8,  9, 10])

In [ ]:
a3=a1[4]+a2[4]
a3

np.int64(15)

In [ ]:
l=[10,20,30,40,50]
arr=np.array(l)
arr

array([10, 20, 30, 40, 50])

In [ ]:
arr+10

array([20, 30, 40, 50, 60])

In [ ]:
a=np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
slice=a[:5]
slice =slice*10
slice

NameError: name 'a' is not defined

In [ ]:
A=np.array([[1, 2],[3, 4]])
B=np.array([[5, 6],[7, 8]])

NameError: name 'np' is not defined

In [ ]:
A

NameError: name 'A' is not defined

In [ ]:
B